### ISSUE TITLE
package_keywords fails to parse package.keywords comment lines

### ISSUE THREAD

**Issue by aetherknight** [gentoo/puppet-portage#139]
# Observed Behavior

During a puppet (4.2.1, installed through portage, running on Ruby 2.0.0) run, I started to get a cryptic error message:

```
Error: Failed to apply catalog: # is not a valid atom
```

Which caused the application of the catalog to fail.

If I enabled `--trace` (`puppet apply --verbose --show_diff --trace /etc/puppetlabs/code/environments/production/manifests/site.pp`) I get the following stack trace:

```
/etc/puppetlabs/code/modules/portage/lib/puppet/util/portage.rb:99:in `parse_atom'
/etc/puppetlabs/code/modules/portage/lib/puppet/provider/portagefile.rb:49:in `process_line'
/etc/puppetlabs/code/modules/portage/lib/puppet/provider/package_keywords/parsed.rb:14:in `block (2 levels) in <top (required)>'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/fileparsing.rb:152:in `handle_record_line'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/fileparsing.rb:245:in `block in parse_line'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/fileparsing.rb:241:in `each'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/fileparsing.rb:241:in `parse_line'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/fileparsing.rb:227:in `block in parse'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/fileparsing.rb:225:in `collect'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/fileparsing.rb:225:in `parse'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/provider/parsedfile.rb:305:in `retrieve'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/provider/parsedfile.rb:265:in `prefetch_target'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/provider/parsedfile.rb:256:in `block in prefetch_all_targets'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/provider/parsedfile.rb:255:in `each'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/provider/parsedfile.rb:255:in `prefetch_all_targets'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/provider/parsedfile.rb:209:in `prefetch'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/transaction.rb:321:in `prefetch'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/transaction.rb:197:in `prefetch_if_necessary'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/transaction.rb:96:in `block in evaluate'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/graph/relationship_graph.rb:116:in `call'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/graph/relationship_graph.rb:116:in `traverse'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/transaction.rb:138:in `evaluate'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/resource/catalog.rb:178:in `block in apply'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/log.rb:153:in `with_destination'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/transaction/report.rb:107:in `as_logging_destination'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/resource/catalog.rb:177:in `apply'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/configurer.rb:119:in `block in apply_catalog'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util.rb:129:in `block in benchmark'
/usr/lib64/ruby/2.0.0/benchmark.rb:296:in `realtime'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util.rb:128:in `benchmark'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/configurer.rb:118:in `apply_catalog'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/configurer.rb:228:in `run_internal'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/configurer.rb:134:in `block in run'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/context.rb:64:in `override'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet.rb:223:in `override'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/configurer.rb:133:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/application/apply.rb:343:in `apply_catalog'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/application/apply.rb:274:in `block in main'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/context.rb:64:in `override'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet.rb:223:in `override'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/application/apply.rb:225:in `main'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/application/apply.rb:170:in `run_command'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/application.rb:344:in `block in run'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util.rb:446:in `exit_on_fail'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/application.rb:344:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/command_line.rb:128:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/lib/puppet/util/command_line.rb:72:in `execute'
/usr/lib64/ruby/gems/2.0.0/gems/puppet-4.2.1/bin/puppet:5:in `<top (required)>'
/usr/bin/puppet:9:in `load'
/usr/bin/puppet:9:in `<main>'
```

I was able to narrow the problem down to one of my package.keywords files:

```
# HEADER: This file was autogenerated at 2015-08-30 23:12:06 -0700
# HEADER: by puppet.  While it can still be managed manually, it
# HEADER: is definitely not recommended.
app-admin/paxtest ~amd64
# required by cargo-bin (argument)
=dev-util/cargo-bin-999 **\n"
```

Based on my testing, the line `# required by cargo-bin (argument)` is causing the problem. It looks like puppet strips off the HEADER lines before it tries to parse the file, but then puppet-portage tries to parse the comment line as if it begins with a package specification atom.
# Expected Behavior

I expect puppet-portage to ignore comment lines when parsing portage files (and/or to otherwise parse it the same way as portage/emerge does), in order to not have failed puppet runs.

**Comment by samuraiii** [comment]
try this https://github.com/gentoo/puppet-portage/pull/142

**Comment by aetherknight** [comment]
@samuraiii Based on my testing, #142 has solved the problem. Thanks!

**Comment by NobbZ** [comment]
I'm using `mod 'gentoo/portage', :git => "https://github.com/gentoo/puppet-portage.git", :branch => "master"`, but I still get this message, and I'm not sure how to deep dive to find the actual file which fails…

```
Error: Failed to apply catalog: # is not a valid atom
/opt/puppetlabs/puppet/cache/lib/puppet/util/portage.rb:99:in `parse_atom'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/portagefile.rb:49:in `process_line'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/package_use/parsed.rb:14:in `block (2 levels) in <top (required)>'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/fileparsing.rb:152:in `handle_record_line'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/fileparsing.rb:245:in `block in parse_line'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/fileparsing.rb:241:in `each'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/fileparsing.rb:241:in `parse_line'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/fileparsing.rb:227:in `block in parse'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/fileparsing.rb:225:in `collect'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/fileparsing.rb:225:in `parse'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/provider/parsedfile.rb:304:in `retrieve'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/provider/parsedfile.rb:265:in `prefetch_target'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/provider/parsedfile.rb:256:in `block in prefetch_all_targets'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/provider/parsedfile.rb:255:in `each'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/provider/parsedfile.rb:255:in `prefetch_all_targets'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/provider/parsedfile.rb:209:in `prefetch'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/transaction.rb:340:in `prefetch'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/transaction.rb:241:in `prefetch_if_necessary'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/transaction.rb:107:in `block in evaluate'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/graph/relationship_graph.rb:119:in `traverse'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/transaction.rb:169:in `evaluate'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/resource/catalog.rb:225:in `block in apply'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/log.rb:155:in `with_destination'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/transaction/report.rb:140:in `as_logging_destination'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/resource/catalog.rb:224:in `apply'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/configurer.rb:172:in `block in apply_catalog'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util.rb:224:in `block in benchmark'
/usr/lib64/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util.rb:223:in `benchmark'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/configurer.rb:171:in `apply_catalog'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/configurer.rb:344:in `run_internal'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/configurer.rb:222:in `block in run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/context.rb:65:in `override'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet.rb:263:in `override'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/configurer.rb:196:in `run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/agent.rb:46:in `block (4 levels) in run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/agent/locker.rb:21:in `lock'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/agent.rb:46:in `block (3 levels) in run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/agent.rb:110:in `with_client'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/agent.rb:43:in `block (2 levels) in run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/agent.rb:67:in `run_in_fork'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/agent.rb:42:in `block in run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/application.rb:179:in `controlled_run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/agent.rb:40:in `run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/application/agent.rb:365:in `onetime'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/application/agent.rb:343:in `run_command'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/application.rb:358:in `block in run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util.rb:666:in `exit_on_fail'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/application.rb:358:in `run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/command_line.rb:132:in `run'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/lib/puppet/util/command_line.rb:72:in `execute'
/usr/lib64/ruby/gems/2.3.0/gems/puppet-5.3.3/bin/puppet:5:in `<top (required)>'
/usr/bin/puppet:9:in `load'
/usr/bin/puppet:9:in `<main>'
```

**Comment by NobbZ** [comment]
I used a small script to remove all comment lines from `package.*` recursively, and now the puppet run was green.  I will leave it as this for now.

**Comment by thesamesam** [comment]
I've pushed 7decc7896a47a08359cb9dd7699055e09d5712ee for package_env, package_mask, package_unmask, package_use too, as well as a 2.6.0 tag containing that.
